# Generated by Django 5.0.3 on 2024-04-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_rename_content_adcomment_adcontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adcomment',
            old_name='adcontent',
            new_name='content',
        ),
    ]
