# Generated by Django 5.0.4 on 2024-04-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_accessed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='last_accessed_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
