# Generated by Django 5.0.4 on 2024-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_last_accessed_time_post_last_accessed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previous_accessed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='previous_accessed_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
