# Generated by Django 5.0.3 on 2024-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Dday',
            field=models.IntegerField(default=0),
        ),
    ]
