# Generated by Django 5.0.3 on 2024-04-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Habit', '취미'), ('Food', '음식'), ('Programming', '프로그래밍')], default='none', max_length=20),
            preserve_default=False,
        ),
    ]
