# Generated by Django 5.0.3 on 2024-04-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Hobby', '취미'), ('Food', '음식'), ('Programming', '프로그래밍'), ('none', '기타')], max_length=20),
        ),
    ]
